import axios from 'axios';
import { writeFile } from 'fs/promises';

const dataArray = [
    "1001002885, Mourad Ahmed Mourad, mourad@egyproperty-eg.com, nan, nan, Chief Executive Officer",
    "1029779927, Fady Hany Fekry Soliman Rezk, f.hany@egyproperty-eg.com, Marketing, nan, Listing Team Leader",
    "1205491512, Bassant Mohamed Mohamed Mohamed Abdelkerem, bassant.a@egyproperty-eg.com, Marketing, nan, Marketing Specialist",
    "1027188309, Mariam Mohamed Helmy Ahmed Ahmed, Mariam.h@egyproperty-eg.com, Marketing, nan, Marketing and Listing Coordinator",
    "1080807561, Sama Mohamed Abdelmordy Ibrahim Omran, sama@egyproperty-eg.com, Marketing, nan, Senior Marketing and Listing Specialist",
    "1004356382, Ahmed Adel Elsayed, a.saad@egyproperty-eg.com, nan, Arm C, Sales Director",
    "1021761388, Sally Gamil Abdelkreem Aly, sgamil@egyproperty-eg.com, Samurai, Arm C, Sales Manager",
    "1011824764, Ahmed Kamal Abdelkreem Mohamed Soliman, a.kamal@egyproperty-eg.com, Eagle, Arm C, Team Leader ",
    "1099708221, Hesham Magdy Ali Mohamed, hesham@egyproperty-eg.com, Samurai, Arm C, Property Advisor",
    "1011422800, Marawan Ayman Hamdy Makhlouf, marwan@egyproperty-eg.com, Samurai, Arm C, Property Advisor",
    "1001822418, Omar Kamal Youness Zakaria ElDesouky Mohamed, omar.k@egyproperty-eg.com, Samurai, Arm C, Property Advisor",
    "1013888101, Salsabel Nasser Mohamed Saad ElDin, Salsabel@egyproperty-eg.com, Sharks, Arm C, Team Leader ",
    "1050714247, Abdelrahman Gamal Mohamed Abdallah, abdelrahman.a@egyproperty-eg.com, Samurai, Arm C, Property Advisor",
    "1080555243, Mohamed Khaled Sayed Ahmed Atia, mohamed.k@egyproperty-eg.com, Strikers, Arm C, Sales Team Leader",
    "1008045786, El Sayed Saad Soliman, khaled.soliman@egyproperty-eg.com, nan, Arm C, Sales Manager",
    "1050061577, Kholoud Ahmed Zakaria Amin ElHakim, k.zakaria@egyproperty-eg.com, HR, nan, Head of Operation & HR",
    "1023832220, Nada Amr Ahmed, n.amr@egyproperty-eg.net, Operation, nan, Sales Operations Manager",
    "1061188139, Mazen Shece, mazen@egyproperty-eg.com, Operation, nan, Senior Sales Operations Specialist",
    "1022441429, Fareeda Sherief Saeed Mohamed, farida@egyproperty-eg.net, Operation, nan, Senior Sales Operations Specialist",
    "1022435454, Hesham Ashraf Salah Mohamed Mahmoud Farag, hesham.af@egyproperty-eg.com, Business Development, nan, Business Developer",
    "1033774819, Radwa Magdy, radwa.magdy@egyproperty-eg.com, Operation, nan, Operation Excutive",
    "1050116802, Manar Mohamed Mohamed, m.aghoury@egyproperty-eg.com, Finance, nan, Finance Supervisor",
    "1017157342, Omar Ahmed Samir Hasan, Omar.a@egyproperty-eg.net, Finance, nan, Accountant",
    "1008766004, Mohamed Adel Mohamed Zaki Abdelfattah, m.zaki@egyproperty-eg.com, nan, Arm A, Sales Director",
    "1029822991, Ahmed Mohamed Dardir Abdelhameed, a.dardiry@egyproperty-eg.com, Alpha, Arm A, Sales Manager",
    "1021199013, Asya Mohamed Shehata Mohamdein Ali Farag, asya@egyproperty-eg.com, Legends, Arm B, Team Leader ",
    "1027766079, Donia Khaled Yakout Ahmed, Donia@egyproperty-eg.com, Diamonds, Arm A, Team Leader ",
    "1011997021, Nada Nasr, nada.nasr@egyproeprty-eg.com, Alpha, Arm A, Property Advisor",
    "1025695550, Abdullah Hesham Ibrahim Abo Hadima, abdullah.h@egyproperty-eg.com, Alpha, Arm A, Property Advisor",
    "1110008935, Mohamed Mekki, Mohamed.ad@egyproperty-eg.com, Marketing, nan, Digital Marketing Supervisor",
    "1112277392, Hana Tarek Ahmed Roshdy Aguiz, Hana.t@egyproperty-eg.com, Marketing, nan, Senior Social Media Specialist and Content Creator",
    "1200531923, Sherif Mohamed Mahrous, sherif.m@egyproperty-eg.com, Alpha, Arm A, Sales Intern",
    "1080442202, Ziad Nasr Abdelrady, ziad.n@egyproperty-eg.com, Alpha, Arm A, Sales Intern",
    "1019664798, Ahmed Zenhom Mohamed Awad, a.zenhom@egyproperty-eg.com, A1, Arm A, Sales Manager",
    "1001800169, Abdelazeem Radwan el ogil, a.ogail@egyproperty-eg.com, Gladiator, Arm A, Team Leader ",
    "1030301844, Karin Ashraf Fawzy Louis, karin@egyproperty-eg.com, Kickers, Arm A, Team Leader ",
    "1070088069, George Hany Milad Hakim, george.h@egyproperty-eg.com, A1, Arm A, Property Advisor",
    "1050013186, Fadi Gehad Mohamed ElSayed Soliman, fady@egyproperty-eg.com, Redbull, Arm A, Sales Manager",
    "1080807568, Mohamed ElGendy, mohamed.gendy@egyproperty-eg.com, A1, Arm A, Property Advisor",
    "1080807564, Gamal Essam Ibrahim, gamal.e@egyproperty-eg.com, Redbull, Arm A, Property Advisor",
    "1099661309, Abdelrahman Zaki Mohamed Zidan ElSheikha, abdelrahman.z@egyproperty-eg.com, The Squad, Arm A, Property Advisor",
    "1050713615, Omar Khaled Zaki Khalil, Omar.za@egyproperty-eg.com, The Squad, Arm A, Property Advisor",
    "1022443036, Mohamed Ashraf Moustafa ElSaeid, M.ashraf@egyproperty-eg.com, 4rent, Arm A, Senior Rental Property Agent",
    "1025593335, Mahmoud Amr Mahmoud ElSayed Ali, mahmoud.ali@egyproperty-eg.com, 4rent, Arm A, Property Rental Agent",
    "1099449587, Yehia Gamal Azeb Elghamry, yehia.g@egyproperty-eg.com, 4rent, Arm A, Real Estate Camp",
    "1070713196, Youssef Alaa Hussien Abdelnaby Hussien, youssef.al@egyproperty-eg.com, 4rent, Arm A, Sales Intern",
    "1019928849, Ahmed Gamal Mohamed Hamed, a.gamal@egyproperty-eg.com, Vikings, Arm E, Sales Director",
    "1030301866, Mariam Mahmoud Ahmed Galal Eldin, Maryam.m@egyproperty-eg.com, Champions, Arm E, Team Leader ",
    "1070088028, Farah Hany Farouk ElGohary, Farah.h@egyproperty-eg.com, Gen Z, Arm E, Team Leader ",
    "1064424460, Youssef Osama ElBastawisy ElSahy, y.bastawisy@egyproperty-eg.com, Cadillacs, Arm E, Team Leader ",
    "1033262857, Gharam Hesham Galal Hemdan, gharam.h@egyproperty-eg.com, nan, nan, CEO assistant",
    "1009467730, Mahmoud Ehab Mahmoud Zaki, mahmoud.e@egyproperty-eg.com, Gen z, Arm E, Property Advisor",
    "1096623693, Mohamed Mohsen Mohamed ElKamel, mohamed.mohsen@egyproperty-eg.com, nan, Arm B, Sales DIrector",
    "1025256195, Fatima Ahmed Abdou Mohamed, fatema@egyproperty-eg.com, Heat, Arm B, Team Leader ",
    "1070925965, Mikhael Mohsen Khalil Malek, mikhael@egyproperty-eg.com, Achievers, Arm B, Team Leader ",
    "1050714249, Omar amer, omar.am@egyproperty-eg.com, Gen z, Arm E, Property Advisor",
    "1069062824, Youmna Ashraf Mahmoud Esmat Taha, youmna@egyproperty-eg.com, Direct Arm B, Arm B, Property Consultant",
    "1029943600, Ahmed Khattab, a.khattab@egyproperty-eg.com, Direct Arm B, Arm B, Property Advisor",
    "1011305162, Mostafa Khattab, m.khattab@egyproperty-eg.com, Vanguards, Arm B, Sales Manager",
    "1001828825, karim Kamil Kamel Rezk, karim.k@egyproperty-eg.com, Archers, Arm B, Team Leader ",
    "1080026217, Heba Mohamed Shawky Ibrahim ElDesouky Abdelfattah, heba.s@egyproperty-eg.com, Fighters, Arm B, Team Leader ",
    "1080807563, Mariam Khaled Mohamed Mohsen Abdelhamed Helmy, mariam.kh@egyproperty-eg.com, Archers, Arm B, Property Advisor",
    "1040888169, Youssef Tamer Abdelraouf Elhaw, youssef.t@egyproperty-eg.com, Vikings, Arm E, Sales Intern",
    "1275011115, Amr Maher Ahmed Elgayar, amr.g@egyproperty-eg.com, nan, nan, Head of Training Specialist",
    "nan, Youssef Hesham Farouk Mohamed ElMehiry, youssef.e@egyproperty-eg.com, The Squad, Arm A, Team Leader ",
    "1050714981, Hany magdy Fawzy, hany.ma@egyproperty-eg.com, Finance, nan, Senior Accounter",
    "1080106636, Noura essam, noura.e@egyproperty-eg.com, Sharks, Arm C, Property Advisor",
    "105 071 3659, Amal Gaber, amal.g@egyproperty-eg.com, Rockstar, Arm A, Team Leader ",
    "1055516135, Habiba Kamal Abd ellatif Abd elhamid elmogy, habiba.k@egyproperty-eg.com, Marketing, nan, Marketing Coordinator",
    "1158857744, Shady mohsen, shady.m@egyproperty-eg.com, Marketing, nan, Junior Social Media Specialist & Events Coordinator",
    "1080106618, Menna ayman, menna.a@egyproperty-eg.com, Redbull, Arm A, Property Advisor",
    "1025611199, Shahinaz El Sayed, Shahinaz.s@egyproperty-eg.com, Heat, Arm B, Property Advisor",
    "1033551563, Haidy Essam, haidy.e@egyproperty-eg.com, Vanguards, Arm B, Property Advisor",
    "1099661321, Ahmed Wael, ahmed.wael@egyproperty-eg.com, Achievers, Arm B, Property Advisor",
    "1033776751, Islam Samy, islam.samy@egyproperty-eg.com, Vikings, Arm E, Team Leader ",
    "1050713658, Omar Asharf, omar.ashraf@egyproperty-eg.com, A1, Arm A, Property Advisor",
    "1050714243, Shahd Hassan, Shahd.h@egyproperty-eg.com, Heat, Arm B, Property Advisor",
    "1033889543, Aya Abdullah Salem , aya.a@egyproperty-eg.com, Marketing, nan, Marketing Listing Spacialist",
    "1020064750, Ahmed Saad, ahmed.sd@egyproperty-eg.com, Finance, nan, chief accounting officer",
    "1099661626, Mohamed El Bialy, muhammed.b@egyproperty-eg.com, Redbull, Arm A, Property Advisor",
    "1033820045, Karim Tarek, Karim.tarek@egyproperty-eg.com, Redbull, Arm A, Team Leader ",
    "1069063167\n1015018666, Maryam Tarek, maryam.t@egyproperty-eg.com, HR, nan, Talent Acquisition Specialist",
    "1025662228, Habiba Hany, habiba.hany@egyproperty-eg.com\n, Vikings, Arm E, Property Advisor",
    "1025626664, Abdelrahman Ahmed , abdelrahman.ah@egyproperty-eg.com, Jaguar, Arm A, Team Leader ",
    "1080305280, Marina Milad, marina.m@egyproperty-eg.com, 4rent, Arm A, Property Rental Agent",
    "nan, Nadeen Ahmed, nadeen.kh@egyproperty-eg.com\n, Marketing, nan, Graphic Designer",
    "1099661764, Reva Bot , nan, nan, nan, nan",
    "1050714964, Nancy Adel, nancy.a@egyproperty-eg.com, Direct Arm B, Arm B, Property Advisor",
    "1033224913, Malak Mansour , malak.m@egyproperty-eg.com, Champions, Arm E, Property Advisor",
    "1200538251, Ahmed Mohsen El Kamel , ahmed.moe@egyproperty-eg.com, Operation , nan, Operation intern",
    "nan, Mouaz Tamer , Moaz.t@egyproperty-eg.com , Operation , nan, Operation intern",
    "1097876025, Rogeh Amel, rogeh.e@egyproperty-eg.com, Achievers, Arm B, Property Advisor",
    "nan, Belal Tamer, belal.t@egyproperty-eg.com, Operation , nan, Operation intern",
    "1065062666, Ali Hassan, ali.hassan@egyproperty-eg.com, Vikings, Arm E, Senior Property Consultant",
    "1029928842, Omar mouslhy, omar.mouslhy@egyproperty-eg.com, Vanguards, Arm B, Property Advisor",
    "1070088156, Abdelrahman Alaa, abdelrahman.be@egyproperty-eg.com, Heat, Arm B, sales intern",
    "1080555237, Nouran ElHusseiny, nouran.hus@egyproperty-eg.com, HR, nan, Talent Acquisition Specialist",
    "1027255814, Nayera Abdelkader, nayira.abd@egyproperty-eg.com, HR, nan, Talent Acquisition Specialist",
    "1027783360, Mohamed Bakr, mohamed.b@egyproperty-eg.com, Fighters, Arm B, Property Advisor",
    "1019446299, Ahmed Medhat, ahmed.med@egyproperty-eg.com, Eagle, Arm C, Sales Intern",
    "1080555245, Jana Ahmed, jana.ahmed@egyproperty-eg.com, Diamonds, Arm A, Sales Intern",
    "1033774120, Mohamed Allam, mohamed.allam@egyproperty-eg.com\n, Vikings, Arm E, Senior Property Consultant",
    "1090138401, Ziad El Snosy, ziad.kassem@egyproperty-eg.com\n, Champions, Arm E, Sales Intern",
    "1033225803, Mahmoud Zenhom, m.zenhom@egyproperty-eg.com, Vikings, Arm E, Property Advisor",
    "1050714979, Nada Mohamed El Saghir, nada.elsaghir@egyproperty-eg.com, Champions, Arm E, Property Advisor",
    "1099084228, Mohamed Ezz, m.ezz@egyproperty-eg.com, Cadillacs, Arm E, Sales Intern",
    "1033225473, Menna Mohamed, menna.moha@egyproperty-eg.com\n, Samurai, Arm C, Property Advisor",
    "1070477119, Engy Mahmoud, engy.marwan@egyproperty-eg.com, Fighters, Arm B, Sales Intern",
    "1080305230, Seif Kadry, seif.kadry@egyproperty-eg.com, Jaguar, Arm A, Property Advisor",
    "1050713613, Mostafa Hareedy, m.hareedy@egyproperty-eg.com, Alpha, Arm A, Senior Property Consultant",
    "1033775128, Mohamed Medhat, mohamed.medhat@egyproperty-eg.com, Gladiator, Arm A, Property Advisor",
    "1050714982, Hassan Salah, hassan.salah@egyproperty-eg.com, Archers, Arm B, Property Advisor",
    "1015650541, Mohamed Awny, mohamed.awny@egyproperty-eg.com, Eagle, Arm C, Sales Intern",
    "1010299776, Salma Raslan, salama.r@egyproperty-eg.com, Vikings, Arm E, Property Advisor",
    "1033224943, Mahmoud Rashed, mahmoud.ra@egyproperty-eg.com, Heat, Arm B, Property consultant",
    "1027252814, Jana Ali Shehab, jana.ehab@egyproperty-eg.com, Hr, nan, Talent Acquisition Spescialist",
    "nan, Mohamed Bayoumi, moh.bayoumi@egyproperty-eg.com, Marketing, nan, Marketing Intern",
    "nan, Roufida Ibrahim, roufida@egyproperty-eg.com\n, HR, nan, Marketing Listing",
    "1020091191, Khaled Metwally, khaled.ahmed@egyproperty-eg.com\n, Champions, Arm E, Property advisor",
    "1025256196, Sherif Ali, sherif.aly@egyproperty-eg.com\n, Gen Z, Arm E, Senior Property Consultant",
    "1050713671, Rawan Hassan, rawan.hassan@egyproperty-eg.com\n, Heat, Arm B, Property advisor",
    "1009548448, Salma Mohamed, salma.g@egyproperty-eg.com\n, 4rent, Arm A , Property Rental Agent",
    "1070230080, Zina Abulsoud, zina.m@egyproperty-eg.com\n, Archers, Arm B, Sales Intern",
    "1001821180, Moaz Al Bakry, moaz.b@egyproperty-eg.com, Gen Z, Arm E, Sales Intern",
    "1094987555, Mazen Alashwah, mazen.alashwah@egyproperty-eg.com, Heat, Arm B, Property Advisor",
    "1001821180, John Hany, john.hany@egyproperty-eg.com\n, Marketing, nan, Marketing",
    "1099649334, Hamza Mohamed, hamza.m@egyproperty-eg.com\n, Heat, Arm B, Sales Intern",
    "1050713591, Remah Wael, remah.w@egyproperty-eg.com\n, Gladiator, Arm A, Sales Intern",
    "1029928874, Wafaa El deeb, wafaa.eldeeb@egyproperty-eg.com, Marketing, nan, Marketing Lisiting",
    "1062389368, Sondos Ashraf, sondos.a@egyproperty-eg.com, Marketing, nan, Marketing Lisiting",
    "1070220870, Hazem El Berry, hazem.elberry@egyproperty-eg.com\n, Fighters, Arm B, Property Advisor",
    "1001335337, Salah ElDien, salah.essam@egyproperty-eg.com\n, Fighters, Arm B, Property Advisor",
    "1029928557, Mohamed Ali Hashem, mohamed.ali@egyproperty-eg.com\n, Archers, Arm B, Property Advisor",
    "1040888170, Abdelrahman Sabry Mohamed, abdelrahman.e@egyproperty-eg.com\n, Gen Z, Arm E, Property Consultant",
    "1040888240, Mohanad Semida, mohanad.s@egyproperty-eg.com\n, Achievers, Arm B, Property Consultant",
    "1014093428, Mohamed Amr, mohamed.amr@egyproperty-eg.com, Sharks, Arm C, Property Advisor",
    "1050713621, Walid Ahmed, walid.a@egyproperty-eg.com, Sharks, Arm C, Property Advisor",
    "1080106620, Malak Hany, malak.hany@egyproperty-eg.com, Hr, nan, Admisitrative officer",
    "nan, Doaa Ismail, nan, Hr, nan, Talent Acquisiton Coordinator ",
    "1099661928, Salma Hesham, salma.hesham@egyproperty-eg.com, Jaguar, Arm A, Property Advisor",
    "1080442201, Bassal Gamal , bassel.sherif@egyproperty-eg.com\n, Jaguar, Arm A, Property Advisor",
    "1080441196, Habiba Mohamed, habiba.mohamed@egyproperty-eg.com\n, Diamonds, Arm A, Property Advisor",
    "1080807567, Mohamed Zakria , m.zakaria@egyproperty-eg.com\n, Cadillacs, Arm E, Property Advisor",
    "1014380225, Mariam Ahmed, mariam.wagdy@egyproperty-eg.com\n, HR, nan, Talent Acquisiton Spescialist",
    "1033225238, Omar Adel Mohamed Abdelhakim, omar.adel@egyproperty-eg.com, Legends, Arm B, Property Advisor",
    "1055516134, Omar Waleed, omar.wal@egyproperty-eg.com\n, Jaguar, Arm A, Property Consultant",
    "1033449168, Abdelrahman Fawzy, abdelrahman.fawzy@egyproperty-eg.com\n, Diamonds, Arm A, Property Advisor",
    "1020092710, Amir Sayed, amir.a@egyproperty-eg.com, Champions, Arm E, Property Advisor",
    "1080140222, Zeyad Mohamed, zeyad.mohamed@egyproperty-eg.com, Champions, Arm E, Property Advisor",
    "1024276888, Mohamed Fayed, m.fayed@egyproperty-eg.com, Eagle, Arm C, Sales Intern",
    "1070088067, Khaled Wahba, khaled.wahba@egyproperty-eg.com, Samurai, Arm C, Property Advisor",
    "1033224754, Youssef Adel, youssef.adel@egyproperty-eg.com, Vikings, Arm E, Property Advisor",
    "1080555259, Omar Abouelfadl, o.aboelfadl@egyproperty-eg.com\n, Business Development, nan, IT",
    "1097608686, Mazen Mohamed, mazen.mohamed@egyproperty-eg.com\n, 4rent, Arm A , Property rental Agent",
    "1070088161, Ahmed Ezzat, ahmed.samir@egyproperty-eg.com, Alpha, Arm A, Property Consultant",
    "1080807562, Sherief Mounir, sherief.mounir@egyproperty-eg.com, Vikings, Arm E, Property Advisor",
    "1097721601, Huda Shawky, hoda.shawky@egyproeprty-eg.com, Vanguards, Arm B, Property Advisor",
    "1062622782, Maryam Chika, maryem.chikwa@egyproperty-eg.com, Fighters, Arm B, Property Consultant",
    "971558555034, Abdallah Alaa Swan , Abdullah@epr.ae, nan, nan, CEO & CO Founder EPR Dubai",
    "1040102655, Sandy Karim, sandy.ka@egyproperty-eg.com, HR, nan, Talent Acquisition",
    "1050713617, Ahmed Farouk, ahmed.fk@egyproperty-eg.com, Cadillacs, Arm E, Property Consultant",
    "1033552408, Seif Hesham, seif.hesham@egyproperty-eg.com, Heat, Arm B, Senior Property Consultant",
    "1050713623, Zeinab Mohamed, zeinab.ib@egyproeprty-eg.com, Champions, Arm E, Property Consultant",
    "1050714971, Marwan Abd Elraheem, marwan.rah@eyproperty-eg.com, Gladiator, Arm A, Property Advisor",
    "1061194422, Hassan Hanafy,  hassan.hanafy@egyproperty-eg.com, Diamonds, Arm A, Property Advisor",
    "nan, Lilan Reda,  lillian.reda@egyproperty-eg.com, Marketing, nan, Video Editor",
    "1099661780, Mostafa Ramdan,  mostafa.ramadan@egyproperty-eg.com, Marketing, nan, Marketing Listing Spacialist",
    "1030115608, Youssef Abdelhakem,  youssef.abdelh@egyproperty-eg.com, A1, Arm A, Property Advisor",
    "1025614999, Youssef Essam,  yousef.essam@egyproperty-eg.com, The Squad, Arm A, Sales Intern",
    "1070088153, Nermeen Kourdy Mahmoud,  nermen.ashraf@egyproperty-eg.com, Achievers, Arm B, Property Advisor",
    "1033558423, Mohaimen Brahim,  mohaimen.ebrahim@egyproperty-eg.com, The Squad, Arm A, Sales Intern",
    "1015018666, Yasmina Mahmoud,  yasmina.mahmoud@egyproeprty-eg.com, HR, nan, Talent Acquisition Coordinator",
    "1080442202, Ziad Osama, ziad.osama@egyproperty-eg.com, diamonds, Arm A, Sales intern",
    "1080305250, Mohamed Gouda , moh.gouda@egyproperty-eg.com, sharks, Arm C, Property advisor",
    "1033225282, Ahmed mosaad, ahmed.mosaad@egyproperty-eg.com, Gen z, Arm E, Property advisor",
    "1070088201, Shahd Ahmed, shahd.ah@egyproperty-eg.com, Epic, Arm B, Property advisor",
    "1030114170, Mohamed Hazem, moh.hazem@egyproperty-eg.com, Redbull, Arm A, Property advisor",
    "1055516131, Bassant Adel, bassant.adel@egyproperty-eg.com, Legends, Arm B, Property advisor",
    "1080555239, Basel Moahmed Galal, bassel.essam@egyproperty-eg.com, Champions, Arm E, Property advisor",
    "1080555243, Hamza Saad, hamza.ahmed@egyproperty-eg.com, Sharks, Arm C, Property advisor",
    "1096527186, yasser youssef, yaser.yo@egyproperty-eg.com, Epic, Arm B, Team Leader",
    "1002353726, Ahella Saleh, ahella.saleh@egyproperty-eg.com, Cadillacs, Arm E, Property advisor",
    "1010301150, Youssef Mohamed, youssef.essam@egyproperty-eg.com, Alpha, Arm A, Property Consultant",
    "1011833225, Basel Fathi, basel.alaa@egyproperty-eg.com, Vikings, Arm E, Property advisor",
    "1050714971, Mohab gheth, mohab.gheith@egyproperty-eg.com, Alpha, Arm A, Property Consultant",
    "1099661548, Nader Labib, nader.nageh@egyproperty-eg.com, Eagle, Arm C, Property advisor",
    "1050713597, Ritaj haitham, ritaj.haitham@egyproperty-eg.com, Jaguar, Arm A, nan",
    "1033775128, Ahmed mahmoud, ahmed.refaee@egyproperty-eg.com, Jaguar, Arm A, nan",
    "1091077990, Ahmed sherif, ahmed.sherif@egyproperty-eg.com, Achievers, Arm B, Property Consultant",
    "1099661439, Ali mokhtar, ali.mokhtar@egyproperty-eg.com, Eagle, Arm C, Property advisor",
    "1055516129, Hana Wafaii, hana.wafai@egyproperty-eg.com, Gen Z, Arm E, Property advisor",
    "1030301229, Hadeer mousa, hadeer.moussa@egyproperty-eg.com, Alpha, Arm A, Sales supervisor",
    "1028356706, Mohanad tarek, mohannad.esmat@egyproperty-eg.com, Legends, Arm B, Property advisor",
    "1001799817, Maha yasser, maha.yasser@egyproperty-eg.com, Champions, Arm E, Property advisor",
    "1070088072, Enjy mohsen, enjy.mohsen@egyproperty-eg.com, Heat, Arm B, Property advisor",
    "1050714245, Abdelrahman mohamed, abdelrahman.ragab@egyproperty-eg.com, Kickers, Arm A, Property advisor",
    "1011817099, Mohamed fayed, mohamed.fayed@egyproperty-eg.com, A1, Arm A, Sales intern",
    "1015620521, Martina mina, martina.mina@egyproperty-eg.com, Rockstars, Arm A, nan",
    "1019990574, Youssef maqlad, youssef.maqlad@egyproperty-eg.com, Fighters, Arm B, Property advisor",
    "1025666286, Abdelrahman el shaarawy, abdelrahman.elshaarawy@egyproperty-eg.com, Epic, Arm B, Property Consultant",
    "1080305252, Janna osama  , janna.osama@egyproperty-eg.com, Fighters, Arm B, nan",
    "1070088168, Fouad, mostafa.almaz@egyproperty-eg.com, Epic, Arm B, Property Consultant",
    "1080441195, Mohamed gharib, mohamed.gharib@egyproperty-eg.com, Vikings, Arm E, Property advisor",
    "1020095299, Yasmeen hosam, yasmeen.hossam@egyproperty-eg.com, Achievers, Arm B, Property advisor",
    "1080988980, Yara mahmoud , yara.mahmoud@egyproperty-eg.com, Vikings, Arm E, Property advisor",
    "1040102655, Gannat ahmed, ganna.ahmed@egyproperty-eg.com, HR, nan, Talent Acquisition Coordinator",
    "1033225101, Ather Waleed, ather.waleed@egyproperty-eg.com, Direct, Arm B, Senior property consultant",
    "1033771380, Nesma Ali, nesma.ali@egyproperty-eg.com, Cadillacs, Arm E, Property advisor",
    "1026693727, Reem Radwan, reem.radwan@egyproperty-eg.com, Cadillacs, Arm E, Property Consultant",
    "1030116471, Mohamed tarek, moh.tarek@egyproperty-eg.com, fighters, Arm B, nan",
    "1003287829, Omar morshedy, omar.morshdy@egyproperty.com, fighters, Arm B, Sales intern",
    "1050713618, Hazem mohamed, hazem.hisham@egyproperty-eg.com, sharks, Arm C, Property advisor",
    "1096662240, Youssef aref, youssef.emad@egyproperty-eg.com, archers, Arm B, Property advisor",
    "1023431051, Rana magdy, rana.magdy2@egyproperty-eg.com, nan, Arm A, Sales Team leader",
    "1023546427, Abdelrahman talaat, abdelrahman.talaat@egyproperty-eg.com, Redbull, Arm A, Property advisor",
    "nan, Ahmed hossam, ahmed.hossam@egyproperty-eg.com, Marketing, nan, Video editor",
    "1050713657, Eman maged ahmed gowaily, eman.maged@egyproperty-eg.com, HR, nan, Talent Acquisition Coordinator",
    "1050713659, Mera abo ramadan, mera.zayed@egyproperty-eg.com, HR, nan, HR Internship",
    "1099661741, Roaa mohamed, roaa.taher@egyproperty-eg.com, HR, nan, Talent Acquisition Coordinator",
    "1050714246, Amr sakr, amr.sakr@egyproperty-eg.com, Eagle, Arm C, Property advisor",
    "1080555240, Moustafa azaab, mostafa.elazab@egyproperty-eg.com, nan, Arm A, Property advisor",
    "1099661358, Mohamed ayman, mohamed.ay@egproperty-eg.com, nan, Arm A, nan"
  ];

const endpoint = 'https://python.dragify.ai/api/agents/universal_rag/chat'; 

const concurrencyLimit = 5;
async function sendRequestsInParallel() {
    let results = [];
  try {
    for (let i = 0; i < dataArray.length; i += concurrencyLimit) {
        let batch = dataArray.slice(i, i + concurrencyLimit);
        const promises = batch.map(item =>
        axios.post(endpoint, {
            "files": [
            "https://docs.google.com/spreadsheets/d/1FI3MZzEshkdV1wQJ1Fbq__StD3CsIJrfFexC_igBpCY/edit?gid=0#gid=0"
            ],
            "question": `Give me contacts for ${item.split(', ')[1].split(' ').slice(0, 2).join(' ')}'s from ${item.split(', ')[3] !== 'nan' ? item.split(', ')[3] : 'any'} team`,
            "instructions": "Return only the phone number and email separated by commas. No further comments or explanations."
        })
        );
        const responses = await Promise.all(promises);
        results = [
          ...results,
          ...responses.map((res, idx) => {
            const actualIndex = i + idx; // i is the batch offset
            return `${dataArray[actualIndex].split(', ')[1]}, ${res.data['friendly_response']}`;
          })
        ];

        await new Promise(resolve => setTimeout(resolve, 1000));
    }

    console.log('All results:', results);

    // Save to result.json
    await writeFile('result.json', JSON.stringify(results, null, 2), 'utf-8');
    console.log('Results saved to result.json');

    return results;
  } catch (error) {
    console.error('One or more requests failed:', error.message || error);
  }
}

const opt = async (arr) => {
  const res = arr.map(item => item.split(', ')[1]);
  await writeFile('names.json', JSON.stringify(res), 'utf-8')
}

opt(dataArray);
